/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.myhealth.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.health.ui.internal.HealthActivator;

public class HealthUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return HealthActivator.getInstance().getInjector("org.xtext.example.myhealth.Health");
	}

}
