/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.myhealth.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class HealthUiModule extends AbstractHealthUiModule {

	public HealthUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
