grammar org.xtext.example.myhealth.Health with org.eclipse.xtext.common.Terminals

generate health "http://www.xtext.org/example/myhealth/Health"

import "http://www.eclipse.org/emf/2002/Ecore" as ecore

HealthProgram:
	statements+=Statement*;
	
Statement:
	PeopleStatement|HeightStatement|WeightStatement|AgeStatement|GenderStatement|IngestStatement|ExerciseStatement|AdviceStatement;
	
	
PeopleStatement:
	'my' 'name' 'is' name=ID
;
HeightStatement:
	'add' 'height' 'as' height=InputValue 'centimeters'
;

WeightStatement:
	'add' 'weight' 'as' weight=InputValue 'kilograms'
;

AgeStatement:
	'add' 'age' 'as' age=InputValue
;

GenderStatement:
	'my' 'gender' 'is' gender=Gender
;

enum Gender:
	Male|Female
;
IngestStatement:
	'I' 'have' nutritiontype=nutrition amount=InputValue 'g'
;

enum nutrition:
	protein|fat|carbohydrate
;

ExerciseStatement:
	'I' ExerciseType= ExerciseType 'for' time=InputValue 'hour'
;

AdviceStatement:
	'give' 'me' 'advice' 'on' ad=AdviceType
;

enum AdviceType:
	Eating|Sport
;

enum ExerciseType:
	walk|run|swim
;

InputValue:
	IntValue|RealValue
;
IntValue:
	val=INT
;
RealValue:
	val=REAL
;
REAL returns ecore::EFloat hidden():
	INT? "." INT
; 