/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.myhealth;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class HealthStandaloneSetup extends HealthStandaloneSetupGenerated {

	public static void doSetup() {
		new HealthStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
