/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.myhealth;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class HealthRuntimeModule extends AbstractHealthRuntimeModule {
}
