/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.myhealth.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class HealthAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/example/myhealth/parser/antlr/internal/InternalHealth.tokens");
	}
}
