/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.myhealth.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.myhealth.parser.antlr.internal.InternalHealthParser;
import org.xtext.example.myhealth.services.HealthGrammarAccess;

public class HealthParser extends AbstractAntlrParser {

	@Inject
	private HealthGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalHealthParser createParser(XtextTokenStream stream) {
		return new InternalHealthParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "HealthProgram";
	}

	public HealthGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(HealthGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
