/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.myhealth.health.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.myhealth.health.AdviceStatement;
import org.xtext.example.myhealth.health.AdviceType;
import org.xtext.example.myhealth.health.HealthPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Advice Statement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.myhealth.health.impl.AdviceStatementImpl#getAd <em>Ad</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AdviceStatementImpl extends StatementImpl implements AdviceStatement
{
  /**
   * The default value of the '{@link #getAd() <em>Ad</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAd()
   * @generated
   * @ordered
   */
  protected static final AdviceType AD_EDEFAULT = AdviceType.EATING;

  /**
   * The cached value of the '{@link #getAd() <em>Ad</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAd()
   * @generated
   * @ordered
   */
  protected AdviceType ad = AD_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AdviceStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return HealthPackage.Literals.ADVICE_STATEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AdviceType getAd()
  {
    return ad;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAd(AdviceType newAd)
  {
    AdviceType oldAd = ad;
    ad = newAd == null ? AD_EDEFAULT : newAd;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HealthPackage.ADVICE_STATEMENT__AD, oldAd, ad));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case HealthPackage.ADVICE_STATEMENT__AD:
        return getAd();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case HealthPackage.ADVICE_STATEMENT__AD:
        setAd((AdviceType)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case HealthPackage.ADVICE_STATEMENT__AD:
        setAd(AD_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case HealthPackage.ADVICE_STATEMENT__AD:
        return ad != AD_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (ad: ");
    result.append(ad);
    result.append(')');
    return result.toString();
  }

} //AdviceStatementImpl
