/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.myhealth.health.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.xtext.example.myhealth.health.AdviceStatement;
import org.xtext.example.myhealth.health.AdviceType;
import org.xtext.example.myhealth.health.AgeStatement;
import org.xtext.example.myhealth.health.ExerciseStatement;
import org.xtext.example.myhealth.health.ExerciseType;
import org.xtext.example.myhealth.health.Gender;
import org.xtext.example.myhealth.health.GenderStatement;
import org.xtext.example.myhealth.health.HealthFactory;
import org.xtext.example.myhealth.health.HealthPackage;
import org.xtext.example.myhealth.health.HealthProgram;
import org.xtext.example.myhealth.health.HeightStatement;
import org.xtext.example.myhealth.health.IngestStatement;
import org.xtext.example.myhealth.health.InputValue;
import org.xtext.example.myhealth.health.IntValue;
import org.xtext.example.myhealth.health.PeopleStatement;
import org.xtext.example.myhealth.health.RealValue;
import org.xtext.example.myhealth.health.Statement;
import org.xtext.example.myhealth.health.WeightStatement;
import org.xtext.example.myhealth.health.nutrition;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class HealthPackageImpl extends EPackageImpl implements HealthPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass healthProgramEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass statementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass peopleStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass heightStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass weightStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ageStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass genderStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ingestStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass exerciseStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass adviceStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass inputValueEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass intValueEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass realValueEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum genderEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum nutritionEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum adviceTypeEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum exerciseTypeEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.xtext.example.myhealth.health.HealthPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private HealthPackageImpl()
  {
    super(eNS_URI, HealthFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link HealthPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static HealthPackage init()
  {
    if (isInited) return (HealthPackage)EPackage.Registry.INSTANCE.getEPackage(HealthPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredHealthPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    HealthPackageImpl theHealthPackage = registeredHealthPackage instanceof HealthPackageImpl ? (HealthPackageImpl)registeredHealthPackage : new HealthPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theHealthPackage.createPackageContents();

    // Initialize created meta-data
    theHealthPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theHealthPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(HealthPackage.eNS_URI, theHealthPackage);
    return theHealthPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getHealthProgram()
  {
    return healthProgramEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getHealthProgram_Statements()
  {
    return (EReference)healthProgramEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getStatement()
  {
    return statementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPeopleStatement()
  {
    return peopleStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPeopleStatement_Name()
  {
    return (EAttribute)peopleStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getHeightStatement()
  {
    return heightStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getHeightStatement_Height()
  {
    return (EReference)heightStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getWeightStatement()
  {
    return weightStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getWeightStatement_Weight()
  {
    return (EReference)weightStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAgeStatement()
  {
    return ageStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAgeStatement_Age()
  {
    return (EReference)ageStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getGenderStatement()
  {
    return genderStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGenderStatement_Gender()
  {
    return (EAttribute)genderStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIngestStatement()
  {
    return ingestStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getIngestStatement_Nutritiontype()
  {
    return (EAttribute)ingestStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getIngestStatement_Amount()
  {
    return (EReference)ingestStatementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExerciseStatement()
  {
    return exerciseStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getExerciseStatement_ExerciseType()
  {
    return (EAttribute)exerciseStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getExerciseStatement_Time()
  {
    return (EReference)exerciseStatementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAdviceStatement()
  {
    return adviceStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAdviceStatement_Ad()
  {
    return (EAttribute)adviceStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getInputValue()
  {
    return inputValueEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIntValue()
  {
    return intValueEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getIntValue_Val()
  {
    return (EAttribute)intValueEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRealValue()
  {
    return realValueEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRealValue_Val()
  {
    return (EAttribute)realValueEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getGender()
  {
    return genderEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getnutrition()
  {
    return nutritionEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getAdviceType()
  {
    return adviceTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getExerciseType()
  {
    return exerciseTypeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public HealthFactory getHealthFactory()
  {
    return (HealthFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    healthProgramEClass = createEClass(HEALTH_PROGRAM);
    createEReference(healthProgramEClass, HEALTH_PROGRAM__STATEMENTS);

    statementEClass = createEClass(STATEMENT);

    peopleStatementEClass = createEClass(PEOPLE_STATEMENT);
    createEAttribute(peopleStatementEClass, PEOPLE_STATEMENT__NAME);

    heightStatementEClass = createEClass(HEIGHT_STATEMENT);
    createEReference(heightStatementEClass, HEIGHT_STATEMENT__HEIGHT);

    weightStatementEClass = createEClass(WEIGHT_STATEMENT);
    createEReference(weightStatementEClass, WEIGHT_STATEMENT__WEIGHT);

    ageStatementEClass = createEClass(AGE_STATEMENT);
    createEReference(ageStatementEClass, AGE_STATEMENT__AGE);

    genderStatementEClass = createEClass(GENDER_STATEMENT);
    createEAttribute(genderStatementEClass, GENDER_STATEMENT__GENDER);

    ingestStatementEClass = createEClass(INGEST_STATEMENT);
    createEAttribute(ingestStatementEClass, INGEST_STATEMENT__NUTRITIONTYPE);
    createEReference(ingestStatementEClass, INGEST_STATEMENT__AMOUNT);

    exerciseStatementEClass = createEClass(EXERCISE_STATEMENT);
    createEAttribute(exerciseStatementEClass, EXERCISE_STATEMENT__EXERCISE_TYPE);
    createEReference(exerciseStatementEClass, EXERCISE_STATEMENT__TIME);

    adviceStatementEClass = createEClass(ADVICE_STATEMENT);
    createEAttribute(adviceStatementEClass, ADVICE_STATEMENT__AD);

    inputValueEClass = createEClass(INPUT_VALUE);

    intValueEClass = createEClass(INT_VALUE);
    createEAttribute(intValueEClass, INT_VALUE__VAL);

    realValueEClass = createEClass(REAL_VALUE);
    createEAttribute(realValueEClass, REAL_VALUE__VAL);

    // Create enums
    genderEEnum = createEEnum(GENDER);
    nutritionEEnum = createEEnum(NUTRITION);
    adviceTypeEEnum = createEEnum(ADVICE_TYPE);
    exerciseTypeEEnum = createEEnum(EXERCISE_TYPE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    peopleStatementEClass.getESuperTypes().add(this.getStatement());
    heightStatementEClass.getESuperTypes().add(this.getStatement());
    weightStatementEClass.getESuperTypes().add(this.getStatement());
    ageStatementEClass.getESuperTypes().add(this.getStatement());
    genderStatementEClass.getESuperTypes().add(this.getStatement());
    ingestStatementEClass.getESuperTypes().add(this.getStatement());
    exerciseStatementEClass.getESuperTypes().add(this.getStatement());
    adviceStatementEClass.getESuperTypes().add(this.getStatement());
    intValueEClass.getESuperTypes().add(this.getInputValue());
    realValueEClass.getESuperTypes().add(this.getInputValue());

    // Initialize classes and features; add operations and parameters
    initEClass(healthProgramEClass, HealthProgram.class, "HealthProgram", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getHealthProgram_Statements(), this.getStatement(), null, "statements", null, 0, -1, HealthProgram.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(statementEClass, Statement.class, "Statement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(peopleStatementEClass, PeopleStatement.class, "PeopleStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPeopleStatement_Name(), ecorePackage.getEString(), "name", null, 0, 1, PeopleStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(heightStatementEClass, HeightStatement.class, "HeightStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getHeightStatement_Height(), this.getInputValue(), null, "height", null, 0, 1, HeightStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(weightStatementEClass, WeightStatement.class, "WeightStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getWeightStatement_Weight(), this.getInputValue(), null, "weight", null, 0, 1, WeightStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(ageStatementEClass, AgeStatement.class, "AgeStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getAgeStatement_Age(), this.getInputValue(), null, "age", null, 0, 1, AgeStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(genderStatementEClass, GenderStatement.class, "GenderStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getGenderStatement_Gender(), this.getGender(), "gender", null, 0, 1, GenderStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(ingestStatementEClass, IngestStatement.class, "IngestStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getIngestStatement_Nutritiontype(), this.getnutrition(), "nutritiontype", null, 0, 1, IngestStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getIngestStatement_Amount(), this.getInputValue(), null, "amount", null, 0, 1, IngestStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(exerciseStatementEClass, ExerciseStatement.class, "ExerciseStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getExerciseStatement_ExerciseType(), this.getExerciseType(), "ExerciseType", null, 0, 1, ExerciseStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getExerciseStatement_Time(), this.getInputValue(), null, "time", null, 0, 1, ExerciseStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(adviceStatementEClass, AdviceStatement.class, "AdviceStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAdviceStatement_Ad(), this.getAdviceType(), "ad", null, 0, 1, AdviceStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(inputValueEClass, InputValue.class, "InputValue", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(intValueEClass, IntValue.class, "IntValue", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getIntValue_Val(), ecorePackage.getEInt(), "val", null, 0, 1, IntValue.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(realValueEClass, RealValue.class, "RealValue", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getRealValue_Val(), ecorePackage.getEFloat(), "val", null, 0, 1, RealValue.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(genderEEnum, Gender.class, "Gender");
    addEEnumLiteral(genderEEnum, Gender.MALE);
    addEEnumLiteral(genderEEnum, Gender.FEMALE);

    initEEnum(nutritionEEnum, nutrition.class, "nutrition");
    addEEnumLiteral(nutritionEEnum, nutrition.PROTEIN);
    addEEnumLiteral(nutritionEEnum, nutrition.FAT);
    addEEnumLiteral(nutritionEEnum, nutrition.CARBOHYDRATE);

    initEEnum(adviceTypeEEnum, AdviceType.class, "AdviceType");
    addEEnumLiteral(adviceTypeEEnum, AdviceType.EATING);
    addEEnumLiteral(adviceTypeEEnum, AdviceType.SPORT);

    initEEnum(exerciseTypeEEnum, ExerciseType.class, "ExerciseType");
    addEEnumLiteral(exerciseTypeEEnum, ExerciseType.WALK);
    addEEnumLiteral(exerciseTypeEEnum, ExerciseType.RUN);
    addEEnumLiteral(exerciseTypeEEnum, ExerciseType.SWIM);

    // Create resource
    createResource(eNS_URI);
  }

} //HealthPackageImpl
