/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.myhealth.health.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.myhealth.health.HealthPackage;
import org.xtext.example.myhealth.health.IngestStatement;
import org.xtext.example.myhealth.health.InputValue;
import org.xtext.example.myhealth.health.nutrition;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Ingest Statement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.myhealth.health.impl.IngestStatementImpl#getNutritiontype <em>Nutritiontype</em>}</li>
 *   <li>{@link org.xtext.example.myhealth.health.impl.IngestStatementImpl#getAmount <em>Amount</em>}</li>
 * </ul>
 *
 * @generated
 */
public class IngestStatementImpl extends StatementImpl implements IngestStatement
{
  /**
   * The default value of the '{@link #getNutritiontype() <em>Nutritiontype</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNutritiontype()
   * @generated
   * @ordered
   */
  protected static final nutrition NUTRITIONTYPE_EDEFAULT = nutrition.PROTEIN;

  /**
   * The cached value of the '{@link #getNutritiontype() <em>Nutritiontype</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNutritiontype()
   * @generated
   * @ordered
   */
  protected nutrition nutritiontype = NUTRITIONTYPE_EDEFAULT;

  /**
   * The cached value of the '{@link #getAmount() <em>Amount</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAmount()
   * @generated
   * @ordered
   */
  protected InputValue amount;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IngestStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return HealthPackage.Literals.INGEST_STATEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public nutrition getNutritiontype()
  {
    return nutritiontype;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNutritiontype(nutrition newNutritiontype)
  {
    nutrition oldNutritiontype = nutritiontype;
    nutritiontype = newNutritiontype == null ? NUTRITIONTYPE_EDEFAULT : newNutritiontype;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HealthPackage.INGEST_STATEMENT__NUTRITIONTYPE, oldNutritiontype, nutritiontype));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public InputValue getAmount()
  {
    return amount;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAmount(InputValue newAmount, NotificationChain msgs)
  {
    InputValue oldAmount = amount;
    amount = newAmount;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, HealthPackage.INGEST_STATEMENT__AMOUNT, oldAmount, newAmount);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAmount(InputValue newAmount)
  {
    if (newAmount != amount)
    {
      NotificationChain msgs = null;
      if (amount != null)
        msgs = ((InternalEObject)amount).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - HealthPackage.INGEST_STATEMENT__AMOUNT, null, msgs);
      if (newAmount != null)
        msgs = ((InternalEObject)newAmount).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - HealthPackage.INGEST_STATEMENT__AMOUNT, null, msgs);
      msgs = basicSetAmount(newAmount, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, HealthPackage.INGEST_STATEMENT__AMOUNT, newAmount, newAmount));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case HealthPackage.INGEST_STATEMENT__AMOUNT:
        return basicSetAmount(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case HealthPackage.INGEST_STATEMENT__NUTRITIONTYPE:
        return getNutritiontype();
      case HealthPackage.INGEST_STATEMENT__AMOUNT:
        return getAmount();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case HealthPackage.INGEST_STATEMENT__NUTRITIONTYPE:
        setNutritiontype((nutrition)newValue);
        return;
      case HealthPackage.INGEST_STATEMENT__AMOUNT:
        setAmount((InputValue)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case HealthPackage.INGEST_STATEMENT__NUTRITIONTYPE:
        setNutritiontype(NUTRITIONTYPE_EDEFAULT);
        return;
      case HealthPackage.INGEST_STATEMENT__AMOUNT:
        setAmount((InputValue)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case HealthPackage.INGEST_STATEMENT__NUTRITIONTYPE:
        return nutritiontype != NUTRITIONTYPE_EDEFAULT;
      case HealthPackage.INGEST_STATEMENT__AMOUNT:
        return amount != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (nutritiontype: ");
    result.append(nutritiontype);
    result.append(')');
    return result.toString();
  }

} //IngestStatementImpl
