/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.myhealth.health;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Advice Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.myhealth.health.AdviceStatement#getAd <em>Ad</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.myhealth.health.HealthPackage#getAdviceStatement()
 * @model
 * @generated
 */
public interface AdviceStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Ad</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.myhealth.health.AdviceType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ad</em>' attribute.
   * @see org.xtext.example.myhealth.health.AdviceType
   * @see #setAd(AdviceType)
   * @see org.xtext.example.myhealth.health.HealthPackage#getAdviceStatement_Ad()
   * @model
   * @generated
   */
  AdviceType getAd();

  /**
   * Sets the value of the '{@link org.xtext.example.myhealth.health.AdviceStatement#getAd <em>Ad</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ad</em>' attribute.
   * @see org.xtext.example.myhealth.health.AdviceType
   * @see #getAd()
   * @generated
   */
  void setAd(AdviceType value);

} // AdviceStatement
