/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.myhealth.health;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Age Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.myhealth.health.AgeStatement#getAge <em>Age</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.myhealth.health.HealthPackage#getAgeStatement()
 * @model
 * @generated
 */
public interface AgeStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Age</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Age</em>' containment reference.
   * @see #setAge(InputValue)
   * @see org.xtext.example.myhealth.health.HealthPackage#getAgeStatement_Age()
   * @model containment="true"
   * @generated
   */
  InputValue getAge();

  /**
   * Sets the value of the '{@link org.xtext.example.myhealth.health.AgeStatement#getAge <em>Age</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Age</em>' containment reference.
   * @see #getAge()
   * @generated
   */
  void setAge(InputValue value);

} // AgeStatement
