/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.myhealth.health;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Gender Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.myhealth.health.GenderStatement#getGender <em>Gender</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.myhealth.health.HealthPackage#getGenderStatement()
 * @model
 * @generated
 */
public interface GenderStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Gender</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.myhealth.health.Gender}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gender</em>' attribute.
   * @see org.xtext.example.myhealth.health.Gender
   * @see #setGender(Gender)
   * @see org.xtext.example.myhealth.health.HealthPackage#getGenderStatement_Gender()
   * @model
   * @generated
   */
  Gender getGender();

  /**
   * Sets the value of the '{@link org.xtext.example.myhealth.health.GenderStatement#getGender <em>Gender</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gender</em>' attribute.
   * @see org.xtext.example.myhealth.health.Gender
   * @see #getGender()
   * @generated
   */
  void setGender(Gender value);

} // GenderStatement
