/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.myhealth.health;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.myhealth.health.HealthFactory
 * @model kind="package"
 * @generated
 */
public interface HealthPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "health";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/myhealth/Health";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "health";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  HealthPackage eINSTANCE = org.xtext.example.myhealth.health.impl.HealthPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.myhealth.health.impl.HealthProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.myhealth.health.impl.HealthProgramImpl
   * @see org.xtext.example.myhealth.health.impl.HealthPackageImpl#getHealthProgram()
   * @generated
   */
  int HEALTH_PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEALTH_PROGRAM__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEALTH_PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.myhealth.health.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.myhealth.health.impl.StatementImpl
   * @see org.xtext.example.myhealth.health.impl.HealthPackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 1;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.myhealth.health.impl.PeopleStatementImpl <em>People Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.myhealth.health.impl.PeopleStatementImpl
   * @see org.xtext.example.myhealth.health.impl.HealthPackageImpl#getPeopleStatement()
   * @generated
   */
  int PEOPLE_STATEMENT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PEOPLE_STATEMENT__NAME = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>People Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PEOPLE_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.myhealth.health.impl.HeightStatementImpl <em>Height Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.myhealth.health.impl.HeightStatementImpl
   * @see org.xtext.example.myhealth.health.impl.HealthPackageImpl#getHeightStatement()
   * @generated
   */
  int HEIGHT_STATEMENT = 3;

  /**
   * The feature id for the '<em><b>Height</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEIGHT_STATEMENT__HEIGHT = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Height Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEIGHT_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.myhealth.health.impl.WeightStatementImpl <em>Weight Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.myhealth.health.impl.WeightStatementImpl
   * @see org.xtext.example.myhealth.health.impl.HealthPackageImpl#getWeightStatement()
   * @generated
   */
  int WEIGHT_STATEMENT = 4;

  /**
   * The feature id for the '<em><b>Weight</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WEIGHT_STATEMENT__WEIGHT = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Weight Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WEIGHT_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.myhealth.health.impl.AgeStatementImpl <em>Age Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.myhealth.health.impl.AgeStatementImpl
   * @see org.xtext.example.myhealth.health.impl.HealthPackageImpl#getAgeStatement()
   * @generated
   */
  int AGE_STATEMENT = 5;

  /**
   * The feature id for the '<em><b>Age</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGE_STATEMENT__AGE = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Age Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGE_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.myhealth.health.impl.GenderStatementImpl <em>Gender Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.myhealth.health.impl.GenderStatementImpl
   * @see org.xtext.example.myhealth.health.impl.HealthPackageImpl#getGenderStatement()
   * @generated
   */
  int GENDER_STATEMENT = 6;

  /**
   * The feature id for the '<em><b>Gender</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENDER_STATEMENT__GENDER = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Gender Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENDER_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.myhealth.health.impl.IngestStatementImpl <em>Ingest Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.myhealth.health.impl.IngestStatementImpl
   * @see org.xtext.example.myhealth.health.impl.HealthPackageImpl#getIngestStatement()
   * @generated
   */
  int INGEST_STATEMENT = 7;

  /**
   * The feature id for the '<em><b>Nutritiontype</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGEST_STATEMENT__NUTRITIONTYPE = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Amount</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGEST_STATEMENT__AMOUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Ingest Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INGEST_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.myhealth.health.impl.ExerciseStatementImpl <em>Exercise Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.myhealth.health.impl.ExerciseStatementImpl
   * @see org.xtext.example.myhealth.health.impl.HealthPackageImpl#getExerciseStatement()
   * @generated
   */
  int EXERCISE_STATEMENT = 8;

  /**
   * The feature id for the '<em><b>Exercise Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXERCISE_STATEMENT__EXERCISE_TYPE = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Time</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXERCISE_STATEMENT__TIME = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Exercise Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXERCISE_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.myhealth.health.impl.AdviceStatementImpl <em>Advice Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.myhealth.health.impl.AdviceStatementImpl
   * @see org.xtext.example.myhealth.health.impl.HealthPackageImpl#getAdviceStatement()
   * @generated
   */
  int ADVICE_STATEMENT = 9;

  /**
   * The feature id for the '<em><b>Ad</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADVICE_STATEMENT__AD = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Advice Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADVICE_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.myhealth.health.impl.InputValueImpl <em>Input Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.myhealth.health.impl.InputValueImpl
   * @see org.xtext.example.myhealth.health.impl.HealthPackageImpl#getInputValue()
   * @generated
   */
  int INPUT_VALUE = 10;

  /**
   * The number of structural features of the '<em>Input Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_VALUE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.myhealth.health.impl.IntValueImpl <em>Int Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.myhealth.health.impl.IntValueImpl
   * @see org.xtext.example.myhealth.health.impl.HealthPackageImpl#getIntValue()
   * @generated
   */
  int INT_VALUE = 11;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_VALUE__VAL = INPUT_VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_VALUE_FEATURE_COUNT = INPUT_VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.myhealth.health.impl.RealValueImpl <em>Real Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.myhealth.health.impl.RealValueImpl
   * @see org.xtext.example.myhealth.health.impl.HealthPackageImpl#getRealValue()
   * @generated
   */
  int REAL_VALUE = 12;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REAL_VALUE__VAL = INPUT_VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Real Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REAL_VALUE_FEATURE_COUNT = INPUT_VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.myhealth.health.Gender <em>Gender</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.myhealth.health.Gender
   * @see org.xtext.example.myhealth.health.impl.HealthPackageImpl#getGender()
   * @generated
   */
  int GENDER = 13;

  /**
   * The meta object id for the '{@link org.xtext.example.myhealth.health.nutrition <em>nutrition</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.myhealth.health.nutrition
   * @see org.xtext.example.myhealth.health.impl.HealthPackageImpl#getnutrition()
   * @generated
   */
  int NUTRITION = 14;

  /**
   * The meta object id for the '{@link org.xtext.example.myhealth.health.AdviceType <em>Advice Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.myhealth.health.AdviceType
   * @see org.xtext.example.myhealth.health.impl.HealthPackageImpl#getAdviceType()
   * @generated
   */
  int ADVICE_TYPE = 15;

  /**
   * The meta object id for the '{@link org.xtext.example.myhealth.health.ExerciseType <em>Exercise Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.myhealth.health.ExerciseType
   * @see org.xtext.example.myhealth.health.impl.HealthPackageImpl#getExerciseType()
   * @generated
   */
  int EXERCISE_TYPE = 16;


  /**
   * Returns the meta object for class '{@link org.xtext.example.myhealth.health.HealthProgram <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see org.xtext.example.myhealth.health.HealthProgram
   * @generated
   */
  EClass getHealthProgram();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.myhealth.health.HealthProgram#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see org.xtext.example.myhealth.health.HealthProgram#getStatements()
   * @see #getHealthProgram()
   * @generated
   */
  EReference getHealthProgram_Statements();

  /**
   * Returns the meta object for class '{@link org.xtext.example.myhealth.health.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see org.xtext.example.myhealth.health.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for class '{@link org.xtext.example.myhealth.health.PeopleStatement <em>People Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>People Statement</em>'.
   * @see org.xtext.example.myhealth.health.PeopleStatement
   * @generated
   */
  EClass getPeopleStatement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.myhealth.health.PeopleStatement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.myhealth.health.PeopleStatement#getName()
   * @see #getPeopleStatement()
   * @generated
   */
  EAttribute getPeopleStatement_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.myhealth.health.HeightStatement <em>Height Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Height Statement</em>'.
   * @see org.xtext.example.myhealth.health.HeightStatement
   * @generated
   */
  EClass getHeightStatement();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.myhealth.health.HeightStatement#getHeight <em>Height</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Height</em>'.
   * @see org.xtext.example.myhealth.health.HeightStatement#getHeight()
   * @see #getHeightStatement()
   * @generated
   */
  EReference getHeightStatement_Height();

  /**
   * Returns the meta object for class '{@link org.xtext.example.myhealth.health.WeightStatement <em>Weight Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Weight Statement</em>'.
   * @see org.xtext.example.myhealth.health.WeightStatement
   * @generated
   */
  EClass getWeightStatement();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.myhealth.health.WeightStatement#getWeight <em>Weight</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Weight</em>'.
   * @see org.xtext.example.myhealth.health.WeightStatement#getWeight()
   * @see #getWeightStatement()
   * @generated
   */
  EReference getWeightStatement_Weight();

  /**
   * Returns the meta object for class '{@link org.xtext.example.myhealth.health.AgeStatement <em>Age Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Age Statement</em>'.
   * @see org.xtext.example.myhealth.health.AgeStatement
   * @generated
   */
  EClass getAgeStatement();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.myhealth.health.AgeStatement#getAge <em>Age</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Age</em>'.
   * @see org.xtext.example.myhealth.health.AgeStatement#getAge()
   * @see #getAgeStatement()
   * @generated
   */
  EReference getAgeStatement_Age();

  /**
   * Returns the meta object for class '{@link org.xtext.example.myhealth.health.GenderStatement <em>Gender Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Gender Statement</em>'.
   * @see org.xtext.example.myhealth.health.GenderStatement
   * @generated
   */
  EClass getGenderStatement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.myhealth.health.GenderStatement#getGender <em>Gender</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Gender</em>'.
   * @see org.xtext.example.myhealth.health.GenderStatement#getGender()
   * @see #getGenderStatement()
   * @generated
   */
  EAttribute getGenderStatement_Gender();

  /**
   * Returns the meta object for class '{@link org.xtext.example.myhealth.health.IngestStatement <em>Ingest Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ingest Statement</em>'.
   * @see org.xtext.example.myhealth.health.IngestStatement
   * @generated
   */
  EClass getIngestStatement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.myhealth.health.IngestStatement#getNutritiontype <em>Nutritiontype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nutritiontype</em>'.
   * @see org.xtext.example.myhealth.health.IngestStatement#getNutritiontype()
   * @see #getIngestStatement()
   * @generated
   */
  EAttribute getIngestStatement_Nutritiontype();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.myhealth.health.IngestStatement#getAmount <em>Amount</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Amount</em>'.
   * @see org.xtext.example.myhealth.health.IngestStatement#getAmount()
   * @see #getIngestStatement()
   * @generated
   */
  EReference getIngestStatement_Amount();

  /**
   * Returns the meta object for class '{@link org.xtext.example.myhealth.health.ExerciseStatement <em>Exercise Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exercise Statement</em>'.
   * @see org.xtext.example.myhealth.health.ExerciseStatement
   * @generated
   */
  EClass getExerciseStatement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.myhealth.health.ExerciseStatement#getExerciseType <em>Exercise Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Exercise Type</em>'.
   * @see org.xtext.example.myhealth.health.ExerciseStatement#getExerciseType()
   * @see #getExerciseStatement()
   * @generated
   */
  EAttribute getExerciseStatement_ExerciseType();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.myhealth.health.ExerciseStatement#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Time</em>'.
   * @see org.xtext.example.myhealth.health.ExerciseStatement#getTime()
   * @see #getExerciseStatement()
   * @generated
   */
  EReference getExerciseStatement_Time();

  /**
   * Returns the meta object for class '{@link org.xtext.example.myhealth.health.AdviceStatement <em>Advice Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Advice Statement</em>'.
   * @see org.xtext.example.myhealth.health.AdviceStatement
   * @generated
   */
  EClass getAdviceStatement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.myhealth.health.AdviceStatement#getAd <em>Ad</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ad</em>'.
   * @see org.xtext.example.myhealth.health.AdviceStatement#getAd()
   * @see #getAdviceStatement()
   * @generated
   */
  EAttribute getAdviceStatement_Ad();

  /**
   * Returns the meta object for class '{@link org.xtext.example.myhealth.health.InputValue <em>Input Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Input Value</em>'.
   * @see org.xtext.example.myhealth.health.InputValue
   * @generated
   */
  EClass getInputValue();

  /**
   * Returns the meta object for class '{@link org.xtext.example.myhealth.health.IntValue <em>Int Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Value</em>'.
   * @see org.xtext.example.myhealth.health.IntValue
   * @generated
   */
  EClass getIntValue();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.myhealth.health.IntValue#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see org.xtext.example.myhealth.health.IntValue#getVal()
   * @see #getIntValue()
   * @generated
   */
  EAttribute getIntValue_Val();

  /**
   * Returns the meta object for class '{@link org.xtext.example.myhealth.health.RealValue <em>Real Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Real Value</em>'.
   * @see org.xtext.example.myhealth.health.RealValue
   * @generated
   */
  EClass getRealValue();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.myhealth.health.RealValue#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see org.xtext.example.myhealth.health.RealValue#getVal()
   * @see #getRealValue()
   * @generated
   */
  EAttribute getRealValue_Val();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.myhealth.health.Gender <em>Gender</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Gender</em>'.
   * @see org.xtext.example.myhealth.health.Gender
   * @generated
   */
  EEnum getGender();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.myhealth.health.nutrition <em>nutrition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>nutrition</em>'.
   * @see org.xtext.example.myhealth.health.nutrition
   * @generated
   */
  EEnum getnutrition();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.myhealth.health.AdviceType <em>Advice Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Advice Type</em>'.
   * @see org.xtext.example.myhealth.health.AdviceType
   * @generated
   */
  EEnum getAdviceType();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.myhealth.health.ExerciseType <em>Exercise Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Exercise Type</em>'.
   * @see org.xtext.example.myhealth.health.ExerciseType
   * @generated
   */
  EEnum getExerciseType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  HealthFactory getHealthFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.myhealth.health.impl.HealthProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.myhealth.health.impl.HealthProgramImpl
     * @see org.xtext.example.myhealth.health.impl.HealthPackageImpl#getHealthProgram()
     * @generated
     */
    EClass HEALTH_PROGRAM = eINSTANCE.getHealthProgram();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HEALTH_PROGRAM__STATEMENTS = eINSTANCE.getHealthProgram_Statements();

    /**
     * The meta object literal for the '{@link org.xtext.example.myhealth.health.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.myhealth.health.impl.StatementImpl
     * @see org.xtext.example.myhealth.health.impl.HealthPackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '{@link org.xtext.example.myhealth.health.impl.PeopleStatementImpl <em>People Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.myhealth.health.impl.PeopleStatementImpl
     * @see org.xtext.example.myhealth.health.impl.HealthPackageImpl#getPeopleStatement()
     * @generated
     */
    EClass PEOPLE_STATEMENT = eINSTANCE.getPeopleStatement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PEOPLE_STATEMENT__NAME = eINSTANCE.getPeopleStatement_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.myhealth.health.impl.HeightStatementImpl <em>Height Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.myhealth.health.impl.HeightStatementImpl
     * @see org.xtext.example.myhealth.health.impl.HealthPackageImpl#getHeightStatement()
     * @generated
     */
    EClass HEIGHT_STATEMENT = eINSTANCE.getHeightStatement();

    /**
     * The meta object literal for the '<em><b>Height</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HEIGHT_STATEMENT__HEIGHT = eINSTANCE.getHeightStatement_Height();

    /**
     * The meta object literal for the '{@link org.xtext.example.myhealth.health.impl.WeightStatementImpl <em>Weight Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.myhealth.health.impl.WeightStatementImpl
     * @see org.xtext.example.myhealth.health.impl.HealthPackageImpl#getWeightStatement()
     * @generated
     */
    EClass WEIGHT_STATEMENT = eINSTANCE.getWeightStatement();

    /**
     * The meta object literal for the '<em><b>Weight</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WEIGHT_STATEMENT__WEIGHT = eINSTANCE.getWeightStatement_Weight();

    /**
     * The meta object literal for the '{@link org.xtext.example.myhealth.health.impl.AgeStatementImpl <em>Age Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.myhealth.health.impl.AgeStatementImpl
     * @see org.xtext.example.myhealth.health.impl.HealthPackageImpl#getAgeStatement()
     * @generated
     */
    EClass AGE_STATEMENT = eINSTANCE.getAgeStatement();

    /**
     * The meta object literal for the '<em><b>Age</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AGE_STATEMENT__AGE = eINSTANCE.getAgeStatement_Age();

    /**
     * The meta object literal for the '{@link org.xtext.example.myhealth.health.impl.GenderStatementImpl <em>Gender Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.myhealth.health.impl.GenderStatementImpl
     * @see org.xtext.example.myhealth.health.impl.HealthPackageImpl#getGenderStatement()
     * @generated
     */
    EClass GENDER_STATEMENT = eINSTANCE.getGenderStatement();

    /**
     * The meta object literal for the '<em><b>Gender</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENDER_STATEMENT__GENDER = eINSTANCE.getGenderStatement_Gender();

    /**
     * The meta object literal for the '{@link org.xtext.example.myhealth.health.impl.IngestStatementImpl <em>Ingest Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.myhealth.health.impl.IngestStatementImpl
     * @see org.xtext.example.myhealth.health.impl.HealthPackageImpl#getIngestStatement()
     * @generated
     */
    EClass INGEST_STATEMENT = eINSTANCE.getIngestStatement();

    /**
     * The meta object literal for the '<em><b>Nutritiontype</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INGEST_STATEMENT__NUTRITIONTYPE = eINSTANCE.getIngestStatement_Nutritiontype();

    /**
     * The meta object literal for the '<em><b>Amount</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INGEST_STATEMENT__AMOUNT = eINSTANCE.getIngestStatement_Amount();

    /**
     * The meta object literal for the '{@link org.xtext.example.myhealth.health.impl.ExerciseStatementImpl <em>Exercise Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.myhealth.health.impl.ExerciseStatementImpl
     * @see org.xtext.example.myhealth.health.impl.HealthPackageImpl#getExerciseStatement()
     * @generated
     */
    EClass EXERCISE_STATEMENT = eINSTANCE.getExerciseStatement();

    /**
     * The meta object literal for the '<em><b>Exercise Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXERCISE_STATEMENT__EXERCISE_TYPE = eINSTANCE.getExerciseStatement_ExerciseType();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXERCISE_STATEMENT__TIME = eINSTANCE.getExerciseStatement_Time();

    /**
     * The meta object literal for the '{@link org.xtext.example.myhealth.health.impl.AdviceStatementImpl <em>Advice Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.myhealth.health.impl.AdviceStatementImpl
     * @see org.xtext.example.myhealth.health.impl.HealthPackageImpl#getAdviceStatement()
     * @generated
     */
    EClass ADVICE_STATEMENT = eINSTANCE.getAdviceStatement();

    /**
     * The meta object literal for the '<em><b>Ad</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADVICE_STATEMENT__AD = eINSTANCE.getAdviceStatement_Ad();

    /**
     * The meta object literal for the '{@link org.xtext.example.myhealth.health.impl.InputValueImpl <em>Input Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.myhealth.health.impl.InputValueImpl
     * @see org.xtext.example.myhealth.health.impl.HealthPackageImpl#getInputValue()
     * @generated
     */
    EClass INPUT_VALUE = eINSTANCE.getInputValue();

    /**
     * The meta object literal for the '{@link org.xtext.example.myhealth.health.impl.IntValueImpl <em>Int Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.myhealth.health.impl.IntValueImpl
     * @see org.xtext.example.myhealth.health.impl.HealthPackageImpl#getIntValue()
     * @generated
     */
    EClass INT_VALUE = eINSTANCE.getIntValue();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_VALUE__VAL = eINSTANCE.getIntValue_Val();

    /**
     * The meta object literal for the '{@link org.xtext.example.myhealth.health.impl.RealValueImpl <em>Real Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.myhealth.health.impl.RealValueImpl
     * @see org.xtext.example.myhealth.health.impl.HealthPackageImpl#getRealValue()
     * @generated
     */
    EClass REAL_VALUE = eINSTANCE.getRealValue();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REAL_VALUE__VAL = eINSTANCE.getRealValue_Val();

    /**
     * The meta object literal for the '{@link org.xtext.example.myhealth.health.Gender <em>Gender</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.myhealth.health.Gender
     * @see org.xtext.example.myhealth.health.impl.HealthPackageImpl#getGender()
     * @generated
     */
    EEnum GENDER = eINSTANCE.getGender();

    /**
     * The meta object literal for the '{@link org.xtext.example.myhealth.health.nutrition <em>nutrition</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.myhealth.health.nutrition
     * @see org.xtext.example.myhealth.health.impl.HealthPackageImpl#getnutrition()
     * @generated
     */
    EEnum NUTRITION = eINSTANCE.getnutrition();

    /**
     * The meta object literal for the '{@link org.xtext.example.myhealth.health.AdviceType <em>Advice Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.myhealth.health.AdviceType
     * @see org.xtext.example.myhealth.health.impl.HealthPackageImpl#getAdviceType()
     * @generated
     */
    EEnum ADVICE_TYPE = eINSTANCE.getAdviceType();

    /**
     * The meta object literal for the '{@link org.xtext.example.myhealth.health.ExerciseType <em>Exercise Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.myhealth.health.ExerciseType
     * @see org.xtext.example.myhealth.health.impl.HealthPackageImpl#getExerciseType()
     * @generated
     */
    EEnum EXERCISE_TYPE = eINSTANCE.getExerciseType();

  }

} //HealthPackage
