/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.myhealth.health;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.myhealth.health.HealthPackage
 * @generated
 */
public interface HealthFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  HealthFactory eINSTANCE = org.xtext.example.myhealth.health.impl.HealthFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Program</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Program</em>'.
   * @generated
   */
  HealthProgram createHealthProgram();

  /**
   * Returns a new object of class '<em>Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement</em>'.
   * @generated
   */
  Statement createStatement();

  /**
   * Returns a new object of class '<em>People Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>People Statement</em>'.
   * @generated
   */
  PeopleStatement createPeopleStatement();

  /**
   * Returns a new object of class '<em>Height Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Height Statement</em>'.
   * @generated
   */
  HeightStatement createHeightStatement();

  /**
   * Returns a new object of class '<em>Weight Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Weight Statement</em>'.
   * @generated
   */
  WeightStatement createWeightStatement();

  /**
   * Returns a new object of class '<em>Age Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Age Statement</em>'.
   * @generated
   */
  AgeStatement createAgeStatement();

  /**
   * Returns a new object of class '<em>Gender Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Gender Statement</em>'.
   * @generated
   */
  GenderStatement createGenderStatement();

  /**
   * Returns a new object of class '<em>Ingest Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ingest Statement</em>'.
   * @generated
   */
  IngestStatement createIngestStatement();

  /**
   * Returns a new object of class '<em>Exercise Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Exercise Statement</em>'.
   * @generated
   */
  ExerciseStatement createExerciseStatement();

  /**
   * Returns a new object of class '<em>Advice Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Advice Statement</em>'.
   * @generated
   */
  AdviceStatement createAdviceStatement();

  /**
   * Returns a new object of class '<em>Input Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Input Value</em>'.
   * @generated
   */
  InputValue createInputValue();

  /**
   * Returns a new object of class '<em>Int Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Int Value</em>'.
   * @generated
   */
  IntValue createIntValue();

  /**
   * Returns a new object of class '<em>Real Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Real Value</em>'.
   * @generated
   */
  RealValue createRealValue();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  HealthPackage getHealthPackage();

} //HealthFactory
