/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.myhealth.health;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Program</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.myhealth.health.HealthProgram#getStatements <em>Statements</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.myhealth.health.HealthPackage#getHealthProgram()
 * @model
 * @generated
 */
public interface HealthProgram extends EObject
{
  /**
   * Returns the value of the '<em><b>Statements</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.myhealth.health.Statement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statements</em>' containment reference list.
   * @see org.xtext.example.myhealth.health.HealthPackage#getHealthProgram_Statements()
   * @model containment="true"
   * @generated
   */
  EList<Statement> getStatements();

} // HealthProgram
