/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.myhealth.health;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Height Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.myhealth.health.HeightStatement#getHeight <em>Height</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.myhealth.health.HealthPackage#getHeightStatement()
 * @model
 * @generated
 */
public interface HeightStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Height</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Height</em>' containment reference.
   * @see #setHeight(InputValue)
   * @see org.xtext.example.myhealth.health.HealthPackage#getHeightStatement_Height()
   * @model containment="true"
   * @generated
   */
  InputValue getHeight();

  /**
   * Sets the value of the '{@link org.xtext.example.myhealth.health.HeightStatement#getHeight <em>Height</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Height</em>' containment reference.
   * @see #getHeight()
   * @generated
   */
  void setHeight(InputValue value);

} // HeightStatement
