/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.myhealth.health;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ingest Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.myhealth.health.IngestStatement#getNutritiontype <em>Nutritiontype</em>}</li>
 *   <li>{@link org.xtext.example.myhealth.health.IngestStatement#getAmount <em>Amount</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.myhealth.health.HealthPackage#getIngestStatement()
 * @model
 * @generated
 */
public interface IngestStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Nutritiontype</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.myhealth.health.nutrition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nutritiontype</em>' attribute.
   * @see org.xtext.example.myhealth.health.nutrition
   * @see #setNutritiontype(nutrition)
   * @see org.xtext.example.myhealth.health.HealthPackage#getIngestStatement_Nutritiontype()
   * @model
   * @generated
   */
  nutrition getNutritiontype();

  /**
   * Sets the value of the '{@link org.xtext.example.myhealth.health.IngestStatement#getNutritiontype <em>Nutritiontype</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nutritiontype</em>' attribute.
   * @see org.xtext.example.myhealth.health.nutrition
   * @see #getNutritiontype()
   * @generated
   */
  void setNutritiontype(nutrition value);

  /**
   * Returns the value of the '<em><b>Amount</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Amount</em>' containment reference.
   * @see #setAmount(InputValue)
   * @see org.xtext.example.myhealth.health.HealthPackage#getIngestStatement_Amount()
   * @model containment="true"
   * @generated
   */
  InputValue getAmount();

  /**
   * Sets the value of the '{@link org.xtext.example.myhealth.health.IngestStatement#getAmount <em>Amount</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Amount</em>' containment reference.
   * @see #getAmount()
   * @generated
   */
  void setAmount(InputValue value);

} // IngestStatement
