/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.myhealth.health;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>nutrition</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.example.myhealth.health.HealthPackage#getnutrition()
 * @model
 * @generated
 */
public enum nutrition implements Enumerator
{
  /**
   * The '<em><b>Protein</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PROTEIN_VALUE
   * @generated
   * @ordered
   */
  PROTEIN(0, "protein", "protein"),

  /**
   * The '<em><b>Fat</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FAT_VALUE
   * @generated
   * @ordered
   */
  FAT(1, "fat", "fat"),

  /**
   * The '<em><b>Carbohydrate</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CARBOHYDRATE_VALUE
   * @generated
   * @ordered
   */
  CARBOHYDRATE(2, "carbohydrate", "carbohydrate");

  /**
   * The '<em><b>Protein</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PROTEIN
   * @model name="protein"
   * @generated
   * @ordered
   */
  public static final int PROTEIN_VALUE = 0;

  /**
   * The '<em><b>Fat</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FAT
   * @model name="fat"
   * @generated
   * @ordered
   */
  public static final int FAT_VALUE = 1;

  /**
   * The '<em><b>Carbohydrate</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CARBOHYDRATE
   * @model name="carbohydrate"
   * @generated
   * @ordered
   */
  public static final int CARBOHYDRATE_VALUE = 2;

  /**
   * An array of all the '<em><b>nutrition</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final nutrition[] VALUES_ARRAY =
    new nutrition[]
    {
      PROTEIN,
      FAT,
      CARBOHYDRATE,
    };

  /**
   * A public read-only list of all the '<em><b>nutrition</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<nutrition> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>nutrition</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static nutrition get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      nutrition result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>nutrition</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static nutrition getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      nutrition result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>nutrition</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static nutrition get(int value)
  {
    switch (value)
    {
      case PROTEIN_VALUE: return PROTEIN;
      case FAT_VALUE: return FAT;
      case CARBOHYDRATE_VALUE: return CARBOHYDRATE;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private nutrition(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //nutrition
