/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.myhealth.health;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Real Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.myhealth.health.RealValue#getVal <em>Val</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.myhealth.health.HealthPackage#getRealValue()
 * @model
 * @generated
 */
public interface RealValue extends InputValue
{
  /**
   * Returns the value of the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' attribute.
   * @see #setVal(float)
   * @see org.xtext.example.myhealth.health.HealthPackage#getRealValue_Val()
   * @model
   * @generated
   */
  float getVal();

  /**
   * Sets the value of the '{@link org.xtext.example.myhealth.health.RealValue#getVal <em>Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' attribute.
   * @see #getVal()
   * @generated
   */
  void setVal(float value);

} // RealValue
