/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.myhealth.health;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Weight Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.myhealth.health.WeightStatement#getWeight <em>Weight</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.myhealth.health.HealthPackage#getWeightStatement()
 * @model
 * @generated
 */
public interface WeightStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Weight</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Weight</em>' containment reference.
   * @see #setWeight(InputValue)
   * @see org.xtext.example.myhealth.health.HealthPackage#getWeightStatement_Weight()
   * @model containment="true"
   * @generated
   */
  InputValue getWeight();

  /**
   * Sets the value of the '{@link org.xtext.example.myhealth.health.WeightStatement#getWeight <em>Weight</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Weight</em>' containment reference.
   * @see #getWeight()
   * @generated
   */
  void setWeight(InputValue value);

} // WeightStatement
