/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.myhealth.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractHealthScopeProvider extends DelegatingScopeProvider {
}
