/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.myhealth.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.myhealth.HealthRuntimeModule;
import org.xtext.example.myhealth.HealthStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class HealthIdeSetup extends HealthStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new HealthRuntimeModule(), new HealthIdeModule()));
	}
	
}
