/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.myhealth.ide;


/**
 * Use this class to register ide components.
 */
public class HealthIdeModule extends AbstractHealthIdeModule {
}
